export const countryMap = [
   { iso3: 'AFG', name: 'Afghanistan', iso2: 'AF' },
   { iso3: 'ALB', name: 'Albania', iso2: 'AL' },
   { iso3: 'DZA', name: 'Algeria', iso2: 'DZ' },
   { iso3: 'AND', name: 'Andorra', iso2: 'AD' },
   { iso3: 'AGO', name: 'Angola', iso2: 'AO' },
   { iso3: 'AIA', name: 'Anguilla', iso2: 'AI' },
   { iso3: 'ATG', name: 'Antigua and Barbuda', iso2: 'AG' },
   { iso3: 'ARG', name: 'Argentina', iso2: 'AR' },
   { iso3: 'ARM', name: 'Armenia', iso2: 'AM' },
   { iso3: 'ABW', name: 'Aruba', iso2: 'AW' },
   { iso3: 'AUS', name: 'Australia', iso2: 'AU' },
   { iso3: 'AUT', name: 'Austria', iso2: 'AT' },
   { iso3: 'AZE', name: 'Azerbaijan', iso2: 'AZ' },
   { iso3: 'BHS', name: 'Bahamas', iso2: 'BS' },
   { iso3: 'BHR', name: 'Bahrain', iso2: 'BH' },
   { iso3: 'BGD', name: 'Bangladesh', iso2: 'BD' },
   { iso3: 'BRB', name: 'Barbados', iso2: 'BB' },
   { iso3: 'BLR', name: 'Belarus', iso2: 'BY' },
   { iso3: 'BEL', name: 'Belgium', iso2: 'BE' },
   { iso3: 'BLZ', name: 'Belize', iso2: 'BZ' },
   { iso3: 'BEN', name: 'Benin', iso2: 'BJ' },
   { iso3: 'BMU', name: 'Bermuda', iso2: 'BM' },
   { iso3: 'BTN', name: 'Bhutan', iso2: 'BT' },
   { iso3: 'BOL', name: 'Bolivia', iso2: 'BO' },
   { iso3: 'BIH', name: 'Bosnia and Herzegovina', iso2: 'BA' },
   { iso3: 'BRA', name: 'Brazil', iso2: 'BR' },
   { iso3: 'VGB', name: 'British Virgin Islands', iso2: 'VG' },
   { iso3: 'BRN', name: 'Brunei', iso2: 'BN' },
   { iso3: 'BGR', name: 'Bulgaria', iso2: 'BG' },
   { iso3: 'BFA', name: 'Burkina Faso', iso2: 'BF' },
   { iso3: 'KHM', name: 'Cambodia', iso2: 'KH' },
   { iso3: 'CMR', name: 'Cameroon', iso2: 'CM' },
   { iso3: 'CAN', name: 'Canada', iso2: 'CA' },
   { iso3: 'CPV', name: 'Cape Verde', iso2: 'CV' },
   { iso3: 'CYM', name: 'Cayman Islands', iso2: 'KY' },
   { iso3: 'CAF', name: 'Central African Republic', iso2: 'CF' },
   { iso3: 'TCD', name: 'Chad', iso2: 'TD' },
   { iso3: 'CHL', name: 'Chile', iso2: 'CL' },
   { iso3: 'CHN', name: 'China', iso2: 'CN' },
   { iso3: 'COL', name: 'Colombia', iso2: 'CO' },
   { iso3: 'COG', name: 'Congo', iso2: 'CG' },
   { iso3: 'CRI', name: 'Costa Rica', iso2: 'CR' },
   { iso3: 'CIV', name: "Cote d'Ivoire", iso2: 'CI' },
   { iso3: 'HRV', name: 'Croatia', iso2: 'HR' },
   { iso3: 'CUB', name: 'Cuba', iso2: 'CU' },
   { iso3: 'CUW', name: 'Curacao', iso2: 'CW' },
   { iso3: 'CYP', name: 'Cyprus', iso2: 'CY' },
   { iso3: 'CZE', name: 'Czech Republic', iso2: 'CZ' },
   { iso3: 'COD', name: 'Democratic Republic of Congo', iso2: 'CD' },
   { iso3: 'DNK', name: 'Denmark', iso2: 'DK' },
   { iso3: 'DJI', name: 'Djibouti', iso2: 'DJ' },
   { iso3: 'DMA', name: 'Dominica', iso2: 'DM' },
   { iso3: 'DOM', name: 'Dominican Republic', iso2: 'DO' },
   { iso3: 'ECU', name: 'Ecuador', iso2: 'EC' },
   { iso3: 'EGY', name: 'Egypt', iso2: 'EG' },
   { iso3: 'SLV', name: 'El Salvador', iso2: 'SV' },
   { iso3: 'GNQ', name: 'Equatorial Guinea', iso2: 'GQ' },
   { iso3: 'ERI', name: 'Eritrea', iso2: 'ER' },
   { iso3: 'EST', name: 'Estonia', iso2: 'EE' },
   { iso3: 'SWZ', name: 'Swaziland', iso2: 'SZ' },
   { iso3: 'ETH', name: 'Ethiopia', iso2: 'ET' },
   { iso3: 'FRO', name: 'Faeroe Islands', iso2: 'FO' },
   { iso3: 'FJI', name: 'Fiji', iso2: 'FJ' },
   { iso3: 'FIN', name: 'Finland', iso2: 'FI' },
   {
      iso3: 'FRA',
      name: 'France',
      iso2: 'FR',
   },
   { iso3: 'PYF', name: 'French Polynesia', iso2: 'PF' },
   { iso3: 'GAB', name: 'Gabon', iso2: 'GA' },
   { iso3: 'GMB', name: 'Gambia', iso2: 'GM' },
   { iso3: 'GEO', name: 'Georgia', iso2: 'GE' },
   {
      iso3: 'DEU',
      name: 'Germany',
      iso2: 'DE',
      expandable: true,
      adminLevels: [
         {
            count: 16,
            name: 'states',
         },
      ],
   },
   { iso3: 'GHA', name: 'Ghana', iso2: 'GH' },
   { iso3: 'GIB', name: 'Gibraltar', iso2: 'GI' },
   { iso3: 'GRC', name: 'Greece', iso2: 'GR' },
   { iso3: 'GRL', name: 'Greenland', iso2: 'GL' },
   { iso3: 'GRD', name: 'Grenada', iso2: 'GD' },
   { iso3: 'GUM', name: 'Guam', iso2: 'GU' },
   { iso3: 'GTM', name: 'Guatemala', iso2: 'GT' },
   { iso3: 'GIN', name: 'Guinea', iso2: 'GN' },
   { iso3: 'GNB', name: 'Guinea-Bissau', iso2: 'GW' },
   { iso3: 'GUY', name: 'Guyana', iso2: 'GY' },
   { iso3: 'HTI', name: 'Haiti', iso2: 'HT' },
   { iso3: 'VAT', name: 'Vatican', iso2: 'VA' },
   { iso3: 'HND', name: 'Honduras', iso2: 'HN' },
   { iso3: 'HUN', name: 'Hungary', iso2: 'HU' },
   { iso3: 'ISL', name: 'Iceland', iso2: 'IS' },
   { iso3: 'IND', name: 'India', iso2: 'IN' },
   { iso3: 'IDN', name: 'Indonesia', iso2: 'ID' },
   { iso3: 'IRN', name: 'Iran', iso2: 'IR' },
   { iso3: 'IRQ', name: 'Iraq', iso2: 'IQ' },
   { iso3: 'IRL', name: 'Ireland', iso2: 'IE' },
   { iso3: 'IMN', name: 'Isle of Man', iso2: 'IM' },
   { iso3: 'ISR', name: 'Israel', iso2: 'IL' },
   {
      iso3: 'ITA',
      name: 'Italy',
      iso2: 'IT',
      expandable: true,
      adminLevels: [
         {
            count: 21,
            name: 'regions',
         },
      ],
   },
   { iso3: 'JAM', name: 'Jamaica', iso2: 'JM' },
   { iso3: 'JPN', name: 'Japan', iso2: 'JP' },
   { iso3: 'JOR', name: 'Jordan', iso2: 'JO' },
   { iso3: 'KAZ', name: 'Kazakhstan', iso2: 'KZ' },
   { iso3: 'KEN', name: 'Kenya', iso2: 'KE' },
   { iso3: 'KOS', name: 'Kosovo' },
   { iso3: 'KWT', name: 'Kuwait', iso2: 'KW' },
   { iso3: 'KGZ', name: 'Kyrgyzstan', iso2: 'KG' },
   { iso3: 'LAO', name: 'Laos', iso2: 'LA' },
   { iso3: 'LVA', name: 'Latvia', iso2: 'LV' },
   { iso3: 'LBN', name: 'Lebanon', iso2: 'LB' },
   { iso3: 'LBR', name: 'Liberia', iso2: 'LR' },
   { iso3: 'LBY', name: 'Libya', iso2: 'LY' },
   { iso3: 'LIE', name: 'Liechtenstein', iso2: 'LI' },
   { iso3: 'LTU', name: 'Lithuania', iso2: 'LT' },
   { iso3: 'LUX', name: 'Luxembourg', iso2: 'LU' },
   { iso3: 'MDG', name: 'Madagascar', iso2: 'MG' },
   { iso3: 'MYS', name: 'Malaysia', iso2: 'MY' },
   { iso3: 'MDV', name: 'Maldives', iso2: 'MV' },
   { iso3: 'MLI', name: 'Mali', iso2: 'ML' },
   { iso3: 'MLT', name: 'Malta', iso2: 'MT' },
   { iso3: 'MRT', name: 'Mauritania', iso2: 'MR' },
   { iso3: 'MUS', name: 'Mauritius', iso2: 'MU' },
   { iso3: 'MEX', name: 'Mexico', iso2: 'MX' },
   { iso3: 'MDA', name: 'Moldova', iso2: 'MD' },
   { iso3: 'MCO', name: 'Monaco', iso2: 'MC' },
   { iso3: 'MNG', name: 'Mongolia', iso2: 'MN' },
   { iso3: 'MNE', name: 'Montenegro', iso2: 'ME' },
   { iso3: 'MSR', name: 'Montserrat', iso2: 'MS' },
   { iso3: 'MAR', name: 'Morocco', iso2: 'MA' },
   { iso3: 'MOZ', name: 'Mozambique', iso2: 'MZ' },
   { iso3: 'MMR', name: 'Myanmar', iso2: 'MM' },
   { iso3: 'NAM', name: 'Namibia', iso2: 'NA' },
   { iso3: 'NPL', name: 'Nepal', iso2: 'NP' },
   { iso3: 'NLD', name: 'Netherlands', iso2: 'NL' },
   { iso3: 'NCL', name: 'New Caledonia', iso2: 'NC' },
   { iso3: 'NZL', name: 'New Zealand', iso2: 'NZ' },
   { iso3: 'NIC', name: 'Nicaragua', iso2: 'NI' },
   { iso3: 'NER', name: 'Niger', iso2: 'NE' },
   { iso3: 'NGA', name: 'Nigeria', iso2: 'NG' },
   { iso3: 'MKD', name: 'Macedonia', iso2: 'MK' },
   { iso3: 'NOR', name: 'Norway', iso2: 'NO' },
   { iso3: 'OMN', name: 'Oman', iso2: 'OM' },
   { iso3: 'PAK', name: 'Pakistan', iso2: 'PK' },
   { iso3: 'PSX', name: 'Palestine' },
   { iso3: 'PAN', name: 'Panama', iso2: 'PA' },
   { iso3: 'PNG', name: 'Papua New Guinea', iso2: 'PG' },
   { iso3: 'PRY', name: 'Paraguay', iso2: 'PY' },
   { iso3: 'PER', name: 'Peru', iso2: 'PE' },
   { iso3: 'PHL', name: 'Philippines', iso2: 'PH' },
   { iso3: 'POL', name: 'Poland', iso2: 'PL' },
   { iso3: 'PRT', name: 'Portugal', iso2: 'PT' },
   { iso3: 'QAT', name: 'Qatar', iso2: 'QA' },
   { iso3: 'ROU', name: 'Romania', iso2: 'RO' },
   { iso3: 'RUS', name: 'Russia', iso2: 'RU' },
   { iso3: 'RWA', name: 'Rwanda', iso2: 'RW' },
   { iso3: 'KNA', name: 'Saint Kitts and Nevis', iso2: 'KN' },
   { iso3: 'LCA', name: 'Saint Lucia', iso2: 'LC' },
   { iso3: 'VCT', name: 'Saint Vincent and the Grenadines', iso2: 'VC' },
   { iso3: 'SMR', name: 'San Marino', iso2: 'SM' },
   { iso3: 'SAU', name: 'Saudi Arabia', iso2: 'SA' },
   { iso3: 'SEN', name: 'Senegal', iso2: 'SN' },
   { iso3: 'SRB', name: 'Serbia', iso2: 'RS' },
   { iso3: 'SYC', name: 'Seychelles', iso2: 'SC' },
   { iso3: 'SGP', name: 'Singapore', iso2: 'SG' },
   { iso3: 'SXM', name: 'Sint Maarten (Dutch part)', iso2: 'SX' },
   { iso3: 'SVK', name: 'Slovakia', iso2: 'SK' },
   { iso3: 'SVN', name: 'Slovenia', iso2: 'SI' },
   { iso3: 'SOM', name: 'Somalia', iso2: 'SO' },
   { iso3: 'ZAF', name: 'South Africa', iso2: 'ZA' },
   { iso3: 'KOR', name: 'South Korea', iso2: 'KR' },
   {
      iso3: 'ESP',
      name: 'Spain',
      iso2: 'ES',
      expandable: true,
   },
   { iso3: 'LKA', name: 'Sri Lanka', iso2: 'LK' },
   { iso3: 'SDN', name: 'Sudan', iso2: 'SD' },
   { iso3: 'SUR', name: 'Suriname', iso2: 'SR' },
   { iso3: 'SWE', name: 'Sweden', iso2: 'SE' },
   { iso3: 'CHE', name: 'Switzerland', iso2: 'CH' },
   { iso3: 'SYR', name: 'Syria', iso2: 'SY' },
   { iso3: 'TWN', name: 'Taiwan', iso2: 'TW' },
   { iso3: 'THA', name: 'Thailand', iso2: 'TH' },
   { iso3: 'TLS', name: 'Timor', iso2: 'TL' },
   { iso3: 'TGO', name: 'Togo', iso2: 'TG' },
   { iso3: 'TTO', name: 'Trinidad and Tobago', iso2: 'TT' },
   { iso3: 'TUN', name: 'Tunisia', iso2: 'TN' },
   { iso3: 'TUR', name: 'Turkey', iso2: 'TR' },
   { iso3: 'TCA', name: 'Turks and Caicos Islands', iso2: 'TC' },
   { iso3: 'UGA', name: 'Uganda', iso2: 'UG' },
   { iso3: 'UKR', name: 'Ukraine', iso2: 'UA' },
   { iso3: 'ARE', name: 'United Arab Emirates', iso2: 'AE' },
   { iso3: 'GBR', name: 'United Kingdom', iso2: 'GB' },
   { iso3: 'TZA', name: 'Tanzania', iso2: 'TZ' },
   { iso3: 'VIR', name: 'United States Virgin Islands', iso2: 'VI' },
   {
      iso3: 'USA',
      name: 'United States',
      iso2: 'US',
   },
   { iso3: 'URY', name: 'Uruguay', iso2: 'UY' },
   { iso3: 'UZB', name: 'Uzbekistan', iso2: 'UZ' },
   { iso3: 'VEN', name: 'Venezuela', iso2: 'VE' },
   { iso3: 'VNM', name: 'Vietnam', iso2: 'VN' },
   { iso3: 'ZMB', name: 'Zambia', iso2: 'ZM' },
   { iso3: 'ZWE', name: 'Zimbabwe', iso2: 'ZW' },
   { iso3: 'PRI', name: 'Puerto Rico', iso2: 'PR' },
   { iso3: 'CUW', name: 'Curacao', iso2: 'CW' },
   //Had to manually add these two countries:
   { iso3: 'GGY', name: 'Guernsey', iso2: 'GG' },
   { iso3: 'JEY', name: 'Jersey', iso2: 'JE' },
];
